# Generated by Django 3.1.7 on 2021-03-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20210315_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='last_name',
        ),
    ]
