# Generated by Django 3.1.7 on 2021-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
