# Generated by Django 3.1.7 on 2021-03-24 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('online', 'Online'), ('tlv', 'Tel Aviv District'), ('central', 'Central District'), ('jerusalem', 'Jerusalem District'), ('haifa', 'Haifa District'), ('north', 'Northern District'), ('south', 'Southern District')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('company', models.CharField(blank=True, max_length=100)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('human_language', models.CharField(choices=[('ENG', 'English'), ('HEB', 'עברית'), ('ARA', 'العربية'), ('RUS', 'Русский'), ('ESP', 'Spanish'), ('FRE', 'Français')], default='English', max_length=15)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.location')),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profiletype')),
                ('skills_have', models.ManyToManyField(related_name='existing', to='accounts.Skill')),
                ('skills_wanted', models.ManyToManyField(related_name='needed', to='accounts.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
