# Generated by Django 3.1.7 on 2021-04-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('online', 'Online'), ('tlv', 'Tel Aviv District'), ('central', 'Central District'), ('jerusalem', 'Jerusalem District'), ('haifa', 'Haifa District'), ('north', 'Northern District'), ('south', 'Southern District')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
