# Generated by Django 3.1.7 on 2021-04-06 09:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210405_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='human_language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'English'), ('HEB', 'עברית'), ('ARA', 'العربية'), ('RUS', 'Русский'), ('ESP', 'Spanish'), ('FRE', 'Français')], default='English', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('online', 'Online'), ('tlv', 'Tel Aviv District'), ('central', 'Central District'), ('jerusalem', 'Jerusalem District'), ('haifa', 'Haifa District'), ('north', 'Northern District'), ('south', 'Southern District')], max_length=9),
        ),
    ]
