# Generated by Django 3.1.7 on 2021-04-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210406_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Human_language',
            new_name='HumanLanguage',
        ),
    ]
